# Data-Driven Business Models (DDBM) – Comparison Table

| DDBM Type | Key Data Sources | Key Activities | Value Proposition | Target Customers | Revenue Model |
|----------|-----------------|----------------|------------------|------------------|---------------|
| **Type A – Free Data Collector and Aggregator** | Mostly free and open data, social media data, crowdsourced data, some proprietary acquired data | Data collection, aggregation, limited crawling, basic visualization, data distribution (e.g., via APIs) | Easy and reliable access to multiple heterogeneous data sources through a single interface | B2B and B2C | Advertising, brokerage fees, subscription fees, usage fees |
| **Type B – Analytics-as-a-Service** | Customer-provided data combined with external datasets | Data collection, analytics, visualization, API-based delivery of insights | Actionable insights and knowledge derived from analytics on customer data (e.g., marketing, fraud detection, customer behavior) | B2B | Subscription fees, usage-based fees |
| **Type C – Data Generation and Analysis** | Self-generated data (tracked, generated, crowdsourced) | Data generation, tracking, aggregation, analytics | Combined data and analytics outputs (e.g., web analytics, leads, performance metrics) | B2B | Usage-based fees, asset sales (e.g., devices, sensors) |
| **Type D – Free Data Knowledge Discovery** | Free and publicly available data (social media, review sites, Q&A platforms, financial and web data) | Web crawling, data aggregation, analytics | Identification and prediction of trends, influencers, and patterns in real time | B2B and B2C | Subscription fees, usage-based fees, advertising, brokerage fees |
| **Type E – Data Aggregation-as-a-Service** | Customer-owned internal data | Data aggregation, organization, visualization, data distribution through interfaces | Structured and unified view of fragmented customer data, simplifying data management | B2B, B2B2C | Subscription fees, usage-based fees |
| **Type F – Multi-Source Data Mashup and Analysis** | Combination of customer-provided data and free/external data (web-scraped) | Data aggregation, data enrichment, analytics, data generation (web scraping) | Enriched and benchmarked analytics by combining internal and external data sources | Mostly B2B | Subscription-based models |
